name: "mind_large"
data_dir: "data/processed/mind_large"

splits:
  train_interactions: "data/processed/mind_large/train/positive_interactions"
  train_pointwise: "data/processed/mind_large/train/pointwise"
  train_impressions: "data/processed/mind_large/train/impressions"
  dev_impressions: "data/processed/mind_large/dev/impressions"
  test_impressions: "data/processed/mind_large/test/impressions"

mappings:
  users: "data/processed/mind_large/mappings/users"
  items: "data/processed/mind_large/mappings/items"

columns:
  user_idx: "user_idx"
  item_idx: "item_idx"
  timestamp: "timestamp"
  candidate_item_idxs: "candidate_item_idxs"
  candidate_seen_in_train_mask: "candidate_seen_in_train_mask"
  candidate_known_mask: "candidate_known_mask"
  history_item_idxs: "history_item_idxs"
  labels: "labels"
